package com.revature.repository;

import com.revature.model.Employee;
import com.revature.utils.ConnectionUtil;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * This class is how [EmployeeService] interacts with the database
 */
public class EmployeeRepository {

    /**
     * This function attempts to add an employee to the database.
     *
     * @param employee The employee to add; should be generated by [EmployeeService]
     */
    public void createNewEmployee(Employee employee){
        String sql = "INSERT INTO Employees (emplEmail, emplPassword, emplRole) values (?, ?, ?)";
        try(Connection con = ConnectionUtil.getConnection()) {
            PreparedStatement prst = con.prepareCall(sql);

            //These replace the question marks in the query with data
            //These use 1-indexing and help prevent SQL injection
            prst.setString(1, employee.getEmail());
            prst.setString(2, employee.getPassword());
            prst.setString(3, employee.getRole().toString());

            prst.execute();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    /**
     * This attempts to log in a user, given an email address and password.
     * I do not yet have the implementation details down, so the void return
     * type should not be considered final.
     *
     * @param email The email address of the employee who is attempting to log in
     * @param password The password of the employee who is attempting to log in
     */
    public void loginEmployee(String email, String password){

    }
}
